# 업데이트 일자 : 2024-02-26
# 연동 기술지원 연락처 : 1600-9854
# 연동 기술지원 이메일 : code@linkhubcorp.com
#
# <테스트 연동개발 준비사항>
# 1) API Key 변경 (연동신청 시 메일로 전달된 정보)
#    - LinkID : 링크허브에서 발급한 링크아이디
#    - SecretKey : 링크허브에서 발급한 비밀키
# 2) SDK 환경설정 옵션 설정
#    - IsTest : 연동환경 설정, true-테스트, false-운영(Production), (기본값:true)
#    - IPRestrictOnOff : 인증토큰 IP 검증 설정, true-사용, false-미사용, (기본값:true)
#    - UseStaticIP : 통신 IP 고정, true-사용, false-미사용, (기본값:false)
#    - UseLocalTimeYN : 로컬시스템 시간 사용여부, true-사용, false-미사용, (기본값:true)

popbill:
  # 링크아이디
  linkId: TESTER
  # 비밀키
  secretKey: SwWxqU+0TErBXy/9TVjIPEnI0VTUMMSQZtJf3Ed8q3I=
  # 연동환경 설정, true-테스트, false-운영(Production), (기본값:true)
  isTest: true
  # 인증토큰 IP 검증 설정, true-사용, false-미사용, (기본값:true)
  isIpRestrictOnOff: true
  # 통신 IP 고정, true-사용, false-미사용, (기본값:false)
  useStaticIp: false
  # 로컬시스템 시간 사용여부, true-사용, false-미사용, (기본값:true)
  useLocalTimeYn: true
  # MLE KEY 사용자 식별 아이디
  mleKeyID: ''
  # MLE KEY 사용자 식별 이름
  mleKeyName: ''
  # MLE 공개키
  mlePublicKey: '''